openapi: 3.0.2
info:
  title: Person API
  version: 1.0.0
paths:

  '/persons':
    get:
      responses:
        200:
          description: List of person.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonList'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonCreate'
      responses:
        201:
          description: Person created.
        422:
          description: Validation error.
          
  '/persons/{person-slug}':
    parameters:
      - name: person-slug
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        200:
          description: Get a specific person.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        404:
          description: Person not found.
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonPatch'
      responses:
        200:
          description: Modifications saved, image returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        404:
          description: Person not found.
        422:
          description: Validation error.

components:

  schemas:

    Translated:
      description: |-
        A translated text under the form of a JSON object
        where the keys are the language code and their value
        is a the translated string.
      additionalProperties:
        type: string
      example:
        en: Hello!
        fr: Bonjour!
        de: Guten Tag!

    WithID:
      description: |-
        A resource with a UUID as its unique identifier.
      type: object
      properties:
        id:
          type: string
          format: UUID
      required:
        - id
    
    WithSlug:
      description: |-
        A resource identifiable by a human-readable
        textual `slug`.
        When getting a resource, the slug is required (provided
        by the server).
      properties:
        slug:
          type: string
      required:
        - slug
        
    WithSlugOpt:
      description: |-
        A resource with an optional slug.
        When creating up updating a resource, it's possible
        to provide a slug that the caller would have decide
        in advance. Needs to be unique on the server for the
        creation/update to succeed.
      properties:
        slug:
          type: string
  
    PersonPatch:
      description: |-
        All properties of a person, all optional.
        Without the ID.
        Used for `PATCH`.
      properties:
        first_name:
          type: string
        last_name:
          type: string
        birthdate:
          type: string
          format: date
        description:
          type: string
        original_name:
          description: Name of the person in its original language(s).
          allOf:
            - $ref: '#/components/schemas/Translated'
    
    PersonReq:
      description: |-
        Pulls all properties from `PersonProps`, defining
        some as required.
      allOf:
        - $ref: '#/components/schemas/PersonPatch'
      required:
        - firstName
        - lastName
        - birthdate

    PersonCreate:
      description: |-
        The `write` version of the resource.
        Providing the `slug` is optional. If not
        provided, the server creates one automatically.
        Used for `POST`.
      allOf:
        - $ref: '#/components/schemas/WithSlugOpt'
        - $ref: '#/components/schemas/PersonReq'
      
    Person:
      description: |-
        The `read` version of the resource.
        The `id` and the `slug` are mandatory in the
        response from the server.
        Used for `GET`.
      allOf:
        - $ref: '#/components/schemas/WithID'
        - $ref: '#/components/schemas/WithSlug'
        - $ref: '#/components/schemas/PersonReq'

    PersonList:
      description: |-
        An object containing a list of person.
      properties:
        data:
          type: array              
          items:
            $ref: '#/components/schemas/PersonListItem'
    
    PersonListItem:
      description: |-
        A person as described as part of a list.
      allOf:
        - $ref: '#/components/schemas/WithID'
        - $ref: '#/components/schemas/WithSlug'
        - properties:
            first_name:
              type: string
            last_name:
              type: string
